// Generated by gencpp from file chapter3_tutorials/SetSpeed.msg
// DO NOT EDIT!


#ifndef CHAPTER3_TUTORIALS_MESSAGE_SETSPEED_H
#define CHAPTER3_TUTORIALS_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <chapter3_tutorials/SetSpeedRequest.h>
#include <chapter3_tutorials/SetSpeedResponse.h>


namespace chapter3_tutorials
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace chapter3_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chapter3_tutorials::SetSpeed > {
  static const char* value()
  {
    return "7baf09683aadda2fb755474c2726a14c";
  }

  static const char* value(const ::chapter3_tutorials::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::chapter3_tutorials::SetSpeed > {
  static const char* value()
  {
    return "chapter3_tutorials/SetSpeed";
  }

  static const char* value(const ::chapter3_tutorials::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::chapter3_tutorials::SetSpeedRequest> should match 
// service_traits::MD5Sum< ::chapter3_tutorials::SetSpeed > 
template<>
struct MD5Sum< ::chapter3_tutorials::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chapter3_tutorials::SetSpeed >::value();
  }
  static const char* value(const ::chapter3_tutorials::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chapter3_tutorials::SetSpeedRequest> should match 
// service_traits::DataType< ::chapter3_tutorials::SetSpeed > 
template<>
struct DataType< ::chapter3_tutorials::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::chapter3_tutorials::SetSpeed >::value();
  }
  static const char* value(const ::chapter3_tutorials::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chapter3_tutorials::SetSpeedResponse> should match 
// service_traits::MD5Sum< ::chapter3_tutorials::SetSpeed > 
template<>
struct MD5Sum< ::chapter3_tutorials::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chapter3_tutorials::SetSpeed >::value();
  }
  static const char* value(const ::chapter3_tutorials::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chapter3_tutorials::SetSpeedResponse> should match 
// service_traits::DataType< ::chapter3_tutorials::SetSpeed > 
template<>
struct DataType< ::chapter3_tutorials::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::chapter3_tutorials::SetSpeed >::value();
  }
  static const char* value(const ::chapter3_tutorials::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHAPTER3_TUTORIALS_MESSAGE_SETSPEED_H
